language: node_js
node_js:
  - "stable"

env:
  XCUBE_VIEWER_VERSION=0.3.2
cache:
  yarn: true
  directories:
    - node_modules
script:
  # - wget https://github.com/dcs4cop/xcube-viewer/archive/v${XCUBE_VIEWER_VERSION}.tar.gz
  # - tar xzvf vv${XCUBE_VIEWER_VERSION}.tar.gz
  - git clone https://github.com/dcs4cop/xcube-viewer
  - cp .env xcube-viewer
  - cd xcube-viewer
  - git checkout dzelge_esdl_branding
  - yarn install
  - yarn run build

deploy:
  - provider: s3
    skip_cleanup: true
    keep-history: true
    local_dir: build
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "eu-central-1"
    endpoint: "s3.eu-central-1.amazonaws.com"
    bucket: "viewer.earthsystemdatalab.net"
    acl: public_read
    on:
      branch: dzelge_chenge_deployment
